%{
rtdsaDataParse
Julian Leland
MIT Media Lab, 2016-12-15

This script parses frequency response data generated by the Simulink DSA to
generate a Bode plot
%}

curDir = 'data/dsaData_2/'; % Change this to point to the correct directory

fileList = dir(curDir); 
fileNames = {}; % Empty cell array to hold names
dsaData_comp = []; % Create empty vector for full DSA data

% Remove directories
for n = 1:length(fileList)
    if ~fileList(n).isdir
        fileNames = [fileNames;fileList(n).name];
    end
end     

% Sort filenames
fileNames_sorted = sort_nat(fileNames);

% Extract data in order (actually, may not have had to do all of this)
for n = 1:length(fileNames_sorted);
    load(strcat(curDir,fileNames_sorted{n}));
    dsaData_comp = [dsaData_comp;freq_resp];
end

dsaData_comp = unique(dsaData_comp,'rows'); % Code was producing duplicate rows - this removes them.

% Data structure is
% [Frequency (rad/s), Magnitude, Phase, ? ? ?]

%% Plot data
figure(1);
subplot(2,1,1);
loglog(dsaData_comp(14:end,1),dsaData_comp(14:end,2))
title('Magnitude');
xlabel('Frequency, rad/s');
ylabel('Magnitude, abs');
subplot(2,1,2);
semilogx(dsaData_comp(14:end,1),dsaData_comp(14:end,3))
title('Phase');
xlabel('Frequency, rad/s');
ylabel('Phase, deg');