function dj2dr = dj2drfcn_at40gw(q2,q3)
%DJ2DRFCN_AT40GW
%    DJ2DR = DJ2DRFCN_AT40GW(Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    10-Feb-2017 10:29:00

t2 = q2+6.136501080547999e1;
t3 = t2.*pi.*(1.0./1.8e2);
t4 = q3-6.83503067849645e1;
t5 = t4.*pi.*(1.0./1.8e2);
dj2dr = reshape([2.048e3,0.0,0.0,0.0,0.0,pi.*sin(t3).*1.0./sqrt(cos(t3).*(-4.28268925668e5)+6.49239431293e5).*(-5.948179523166667e1),0.0,0.0,0.0,0.0,pi.*sin(t5).*1.0./sqrt(cos(t5).*(-9.009209832499999e5)+1.50409067285e6).*8.341860956018518e1,0.0,0.0,0.0,0.0,2.0./3.35e2],[4,4]);
