function FK1 = fkine_J1_at40gw(Theta_1, Theta_2, Theta_3, D_4)
%FKINE_J1_AT40GW
%    FK1 = FKINE_J1_AT40GW(THETA_1)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    26-Jan-2017 15:14:38

t2 = Theta_1.*pi.*(1.0./1.8e2);
t3 = sin(t2);
t4 = cos(t2);
FK1 = reshape([1.0,0.0,0.0,7.113e2,0.0,t4,t3,0.0,0.0,-t3,t4,0.0,0.0,0.0,0.0,1.0],[4,4]);
