function j2r = j2rfcn_at40gw(q1,q2,q3,q4)
%J2RFCN_AT40GW
%    J2R = J2RFCN_AT40GW(Q1,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    24-Jul-2017 12:59:37

j2r = [q1.*(5.0./2.88e2)+5.0,sqrt(cos(pi.*(q2+6.136501080547999e1).*(1.0./1.8e2)).*(-4.28268925668e5)+6.49239431293e5).*(-1.0./2.0e1)+4.01067e1,sqrt(cos(pi.*(q3-6.83503067849645e1).*(1.0./1.8e2)).*(-9.009209832499999e5)+1.50409067285e6).*(1.0./3.0e1)-3.95619e1,q4.*(2.0./3.35e2)-3.97e2./4.0e1];
